In [9]:
# STEP 1: IMPORT LIBRARIES
import pandas as pd
import numpy as np

# STEP 2: LOAD DATASET
df = pd.read_csv("dresses.csv")
print("Dataset loaded successfully\n")

print("First 5 rows:")
display(df.head())

print("\nLast 5 rows:")
display(df.tail())

print("\nShape of dataset (rows, columns):")
print(df.shape)

print("\nColumn names:")
print(df.columns)

print("\nData types of each column:")
print(df.dtypes)

print("\nBasic info about dataset:")
df.info()

# STEP 3: MISSING VALUES CHECK
print("\nMissing values before cleaning:")
print(df.isnull().sum())

num_cols = df.select_dtypes(include=np.number).columns
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

print("\nMissing values after cleaning:")
print(df.isnull().sum())

# STEP 4: REMOVE DUPLICATES
before = df.shape[0]
df = df.drop_duplicates()
after = df.shape[0]

print(f"\nNumber of duplicate rows removed: {before - after}")

# STEP 5: CLEANING PRICE COLUMN
df['final_price'] = (
    df['final_price']
    .astype(str)
    .str.replace(r'[₹,"]', '', regex=True)
    .str.strip()
)

df['final_price'] = pd.to_numeric(df['final_price'], errors='coerce')

# STEP 6: FEATURE ENGINEERING

df['quantity'] = 2
df['total_amount'] = df['final_price'] * df['quantity']

# STEP 7: FILTERING DATA + BASIC INSIGHTS + SAVE CLEANED FILE
print("\nShowing products with rating greater than 4:")
display(df[df['rating'] > 4])

print("\nSome basic insights from data:")
print("Average rating:", df['rating'].mean())
print("Maximum price:", df['final_price'].max())
print("Minimum price:", df['final_price'].min())

df.to_csv("cleaned_dresses.csv", index=False)
print("\nCleaned dataset saved successfully as cleaned_dresses.csv")

# SUMMARY

print("""
FINAL SUMMARY:

- Worked on a dresses dataset containing product details like rating, price, discount, seller info, and categories.

- Loaded the dataset and explored its structure using head(), tail(), shape, columns, data types, and info().

- Checked missing values in columns such as discount, seller_name, what_customers_said, videos, and variations.

- Handled missing values by filling numeric columns with median and categorical columns with mode.

- Removed duplicate rows to ensure clean and accurate data.

- Cleaned the final_price column by removing currency symbols (₹) and converting it into numeric format.

- Created a new feature called total_amount using final_price × quantity.

- Performed filtering to display products with rating greater than 4.

- Generated basic insights such as average rating, maximum price, and minimum price from the dataset.

- Saved the cleaned dataset as 'cleaned_dresses.csv' for further analysis.
""")

Dataset loaded successfully

First 5 rows:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,21664722,Curvy Clan,Colourblocked A-Line Cotton Maxi Dress,3.7,3,2999.0,NaN,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,RUB███S C███,"[{""size"":""XL"",""value"":""42.0in"",""value_name"":""B...",NaN,"604███TH ███OR,█████████ITA███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
1,21426422,Trendyol,Black Maxi Dress,4.1,10,4399.0,45.0,"""₹2,419.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
2,21238004,COVER STORY,Embellished Shoulder Straps Velvet Sheath Dress,4.8,24,3490.0,40.0,"""₹2,094.00""",INR,http://assets.myntassets.com/assets/images/212...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Cov███Sto███Clo█████████ite███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Kil███5/1███ 18█████████ 22███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
3,21426632,Trendyol,Floral Printed Shoulder strap A-Line Mini Dress,3.9,35,3599.0,30.0,"""₹2,519.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":6,""2_stars"":2,""3_stars"":1,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
4,21673378,RACHNA,Floral Print Flared Sleeve Crepe A-Line Mini D...,3.0,4,1299.0,51.0,"""₹628.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,RAC███ AR███RIN█████████TD.███,"[{""size"":""M"",""value"":""38.0in"",""value_name"":""Bu...",NaN,243███244███ Pa█████████rat█████████████████████,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses

Last 5 rows:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
95,22630128,NUEVOSDAMAS,Girls Polka Dot Printed Crepe Fit & Flare Dress,2.8,5,1999.0,70.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,M/S███V M███C.,"[{""size"":""2-3Y"",""value"":""22.0in"",""value_name"":...",NaN,"D-2███09,███CTO█████████ , █████████████████████1",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
96,22610562,NIGHTSPREE,Band Collar Floral Printed Maternity Fit & Fla...,0.0,0,2299.0,50.0,"""₹1,149.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,MAH███R E███RPR██████,"[{""size"":""M"",""value"":""48.0in"",""value_name"":""Fr...",NaN,"C B███K, ███ FL█████████HEB███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
97,22596522,Vero Moda,Shoulder Straps Cut Out Smocked A-Line Midi Dress,4.3,12,3799.0,65.0,"""₹1,329.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",VER███ODA███TAI█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,4th███oor███he █████████ide███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
98,22619942,Styli,Burgundy Puff Sleeve Accordion Pleated Fit & F...,3.7,11,2799.0,51.0,"""₹1,371.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",PRE███RE ███AIL█████████PRI███████████████,"[{""size"":""S"",""value"":""33.1in"",""value_name"":""To...",NaN,KHA███ NO███/13█████████8/2███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
99,13400194,Style Quotient,Girls Navy Blue Striped Drop-Waist Dress,0.0,0,1299.0,73.0,"""₹350.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Kri███n S███het█████████td,"[{""size"":""2-3Y"",""value"":""9.0in"",""value_name"":""...",NaN,"615███hur███ate█████████,5 ███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses

Shape of dataset (rows, columns):
(100, 24)

Column names:
Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

Data types of each column:
product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

Basic info about dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              100 non-null    int64
 1   title                   100 non-null    object
 2   product_description     100 non-null    object
 3   rating                  100 non-null    float64
 4   ratings_count           100 non-null    int64
 5   initial_price           100 non-null    float64
 6   discount                92 non-null     float64
 7   final_price             100 non-null    object
 8   currency                100 non-null    object
 9   images                  100 non-null    object
 10  delivery_options        100 non-null    object
 11  product_details         100 non-null    object
 12  breadcrumbs             100 non-null    object
 13  product_specifications  100 non-null    object
 14  amount_of_stars         100 non-null    object
 15  what_customers_said     63 non-null     object
 16  seller_name             90 non-null     object
 17  sizes                   100 non-null    object
 18  videos                  10 non-null     object
 19  seller_information      90 non-null     object
 20  variations              39 non-null     object
 21  best_offer              100 non-null    object
 22  more_offers             100 non-null    object
 23  category                100 non-null    object
dtypes: float64(3), int64(2), object(19)
memory usage: 18.9+ KB

Missing values before cleaning:
product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   8
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said       37
seller_name               10
sizes                      0
videos                    90
seller_information        10
variations                61
best_offer                 0
more_offers                0
category                   0
dtype: int64

Missing values after cleaning:
product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

Number of duplicate rows removed: 0

Showing products with rating greater than 4:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
1,21426422,Trendyol,Black Maxi Dress,4.1,10,4399.0,45.0,2419.0,INR,http://assets.myntassets.com/assets/images/214...,...,Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,4838.0
2,21238004,COVER STORY,Embellished Shoulder Straps Velvet Sheath Dress,4.8,24,3490.0,40.0,2094.0,INR,http://assets.myntassets.com/assets/images/212...,...,Cov███Sto███Clo█████████ite███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",Kil███5/1███ 18█████████ 22███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,4188.0
8,21664974,Label Ritu Kumar,Candy Striped Pure Cotton Wrap Dress,4.6,7,4500.0,30.0,3150.0,INR,http://assets.myntassets.com/assets/images/216...,...,REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",Rel███ce ███uku█████████Ltd███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,6300.0
13,22004792,WoowZerz,Button Detailed Mini Blazer Dress,4.8,26,2495.0,50.0,1247.0,INR,http://assets.myntassets.com/assets/images/220...,...,Man███ Fa███ona██████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",B-8███2nd███oor█████████r I███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,2494.0
17,18962984,Athena,Burgundy Off-Shoulder Scrunchie Bodycon Dress,4.3,236,2499.0,68.0,799.0,INR,http://assets.myntassets.com/assets/images/189...,...,APE███PPA███S,"[{""size"":""XS"",""value"":""8.0in"",""value_name"":""Sl...","[""https://videos.myntassets.com/assets/videos/...","Plo███o. ███, P█████████2Se███████████████████...","[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1598.0
21,18977246,AURELIA,Blue Ethnic Motifs Maxi Dress,4.1,140,4299.0,59.0,1750.0,INR,http://assets.myntassets.com/assets/images/189...,...,Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",Vil███e B███a B█████████ata███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,3500.0
23,18962990,Athena,Teal Blue Side Gathered Maxi Dress,4.2,35,2499.0,66.0,849.0,INR,http://assets.myntassets.com/assets/images/189...,...,APE███PPA███S,"[{""size"":""XS"",""value"":""32.5in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...","Plo███o. ███, P█████████2Se███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1698.0
25,18956684,Forevermore,Mustard Yellow Chiffon Embroidred Ruffle Tiere...,4.2,5,1599.0,63.0,1599.0,INR,http://assets.myntassets.com/assets/images/189...,...,Ami███nte███ise███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...","[""https://videos.myntassets.com/assets/videos/...",10/███CHH███YA █████████ILL███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,3198.0
26,18981160,Amydus,Blue & Orange Floral Wrap Dress,4.7,43,2799.0,63.0,2799.0,INR,http://assets.myntassets.com/assets/images/189...,...,BEG███01 ███EST██████,"[{""size"":""XXL"",""value"":""41.0in"",""value_name"":""...","[""https://videos.myntassets.com/assets/videos/...","357███has███, U█████████r, ███████████████████...","[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,5598.0
27,18962952,Athena,Lavender Solid Accordion Pleats Wrap Dress,4.2,3797,2799.0,60.0,1119.0,INR,http://assets.myntassets.com/assets/images/189...,...,Ape███ppa███s -██████,"[{""size"":""XS"",""value"":""23.0in"",""value_name"":""S...","[""https://videos.myntassets.com/assets/videos/...","Plo███o. ███, P█████████2 S███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,2238.0
30,15788324,Tokyo Talkies,Blue Off-Shoulder Maxi Dress,4.2,347,1399.0,53.0,475.0,INR,http://assets.myntassets.com/assets/images/157...,...,Vis███ St███,"[{""size"":""S"",""value"":""35.0in"",""value_name"":""Bu...","[""https://videos.myntassets.com/assets/videos/...",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,950.0
32,15691070,QUIERO,Women Beautiful Orange Abstract Tiered Dress,4.1,474,2820.0,65.0,987.0,INR,http://assets.myntassets.com/assets/images/156...,...,Per███nkl███esi██████,"[{""size"":""XS"",""value"":""40.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",B-1███1st███2nd█████████tor███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1974.0
33,13770986,all about you,Black Solid Midi Halter Neck Fit and Flare Dress,4.2,38,2999.0,63.0,2999.0,INR,http://assets.myntassets.com/assets/images/137...,...,REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","[""rw-13770986_cae700""]",3rd███oor███o. █████████Mai███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",dresses,2,5998.0
36,17592092,U&F,Women Stylish Mustard Solid All in the Details...,4.1,7,2899.0,74.0,753.0,INR,http://assets.myntassets.com/assets/images/175...,...,SVP███XPO███ PR█████████ITE███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""https://videos.myntassets.com/assets/videos/...","A-4███ect███7 N█████████ , █████████████████████1","[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1506.0
37,17661682,Tokyo Talkies,Lavender Cut Outs Sheath Mini Dress,4.1,13,1549.0,61.0,340.0,INR,http://assets.myntassets.com/assets/images/176...,...,Vis███ St███,"[{""size"":""XS"",""value"":""30.0in"",""value_name"":""B...","[""rw-17661682_cae700"",""https://videos.myntasse...",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,680.0
38,17692718,Style Quotient,Women Tranquil Teal Solid Halter Neck Dress,4.8,8,1599.0,69.0,495.0,INR,http://assets.myntassets.com/assets/images/176...,...,Kri███n S███het█████████td,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""https://videos.myntassets.com/assets/videos/...","615███hur███ate█████████,5 ███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,990.0
39,17194598,Tokyo Talkies,Women Charming Purple Solid Dress,4.3,48,1749.0,65.0,437.0,INR,http://assets.myntassets.com/assets/images/171...,...,Vis███ St███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""B...","[""rw-17194598_cae700""]",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,874.0
40,17194592,Tokyo Talkies,Women Stunning Blue Solid Dress,4.1,240,1749.0,65.0,367.0,INR,http://assets.myntassets.com/assets/images/171...,...,Vis███ St███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,734.0
41,18207478,Tokyo Talkies,Women Gorgeous Green Solid Dress,4.1,333,699.0,60.0,279.0,INR,http://assets.myntassets.com/assets/images/182...,...,Vis███ St███,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",3rd███oor███o. █████████Mai███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,558.0
43,18996672,Bella Moda,Girls Yellow & Navy Blue Fit and Flare Dress,4.6,8,2017.0,70.0,605.0,INR,http://assets.myntassets.com/assets/images/189...,...,SHI███TRA███S,"[{""size"":""1-2Y"",""value"":""21.0in"",""value_name"":...","[""https://videos.myntassets.com/assets/videos/...","642███H F███R,J█████████LIS███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1210.0
46,19213200,Label Ritu Kumar,Cream-Coloured & Blue Ethnic Motifs Georgette ...,4.8,5,5200.0,40.0,3120.0,INR,http://assets.myntassets.com/assets/images/192...,...,REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",Rel███ce ███uku█████████Ltd███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,6240.0
50,19987092,Vastralay,Grey & Black Tie and Dye Dyed Midi Dress,4.2,17,2999.0,78.0,659.0,INR,http://assets.myntassets.com/assets/images/199...,...,ASH███ PR███S,"[{""size"":""S"",""value"":""35.0in"",""value_name"":""To...","[""https://videos.myntassets.com/assets/videos/...","ASH███ PR███S, █████████CTO███████████████████...","[{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1318.0
51,10054817,Veni Vidi Vici,Women Mustard Yellow Bodycon Dress,4.3,110,1890.0,60.0,756.0,INR,http://assets.myntassets.com/assets/images/100...,...,NYM███EA ███HIO█████████ PR███████████████,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...","140███1, ███JAR█████████UTA███████████████████...","[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1512.0
52,10054855,Veni Vidi Vici,Solid Olive Green Ruched Bodycon Dress,4.2,389,1890.0,60.0,756.0,INR,http://assets.myntassets.com/assets/images/100...,...,NYM███EA ███HIO█████████ PR███████████████,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...","140███1, ███JAR█████████UTA███████████████████...","[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1512.0
53,10691426,SASSAFRAS,Black & Beige Ikat Print Cotton Shirt Dress,4.5,4441,2199.0,65.0,769.0,INR,http://assets.myntassets.com/assets/images/106...,...,ARD███ Re███l C███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",Khe███ No███76/█████████il ███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1538.0
55,18963006,Athena,Purple Off-Shoulder Scrunchie Bodycon Dress,4.3,45,2499.0,68.0,799.0,INR,http://assets.myntassets.com/assets/images/189...,...,APE███PPA███S,"[{""size"":""XS"",""value"":""8.0in"",""value_name"":""Sl...","[""https://videos.myntassets.com/assets/videos/...","Plo███o. ███, P█████████2Se███████████████████...","[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1598.0
56,19513066,Stylecast X Hersheinbox,Floral Fit & Flare Dress With Gathered Details,4.5,11,2559.0,54.0,2559.0,INR,http://assets.myntassets.com/assets/images/195...,...,REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","[""rw-19513066_cae700""]",3rd███oor███o. █████████Mai███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",dresses,2,5118.0
58,18975316,Berrylush,Women Off-White Striped Knits Bits Dress,4.2,31,3200.0,74.0,640.0,INR,http://assets.myntassets.com/assets/images/189...,...,Sup███om ███,"[{""size"":""S"",""value"":""33.0in"",""value_name"":""Fr...","[""https://videos.myntassets.com/assets/videos/...",Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1280.0
60,21242962,Tommy Hilfiger,Sustainable Pure Cotton Denim Shirt Dress With...,4.4,9,5999.0,40.0,5699.0,INR,http://assets.myntassets.com/assets/images/212...,...,Fla███ech███tai███,"[{""size"":""XXS"",""value"":""30.5in"",""value_name"":""...","[""rw-21242962_cae700""]","3rd███165███th █████████, s███████████████████...",[{}],"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,11398.0
61,21653646,ONLY,Floral Printed A-Line Dress,4.6,5,3299.0,60.0,1319.0,INR,http://assets.myntassets.com/assets/images/216...,...,ONL███ETA███PVT██████,"[{""size"":""XS"",""value"":""17.7in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",5th███oor███he █████████ide███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,2638.0
63,20022902,Slenor,Women Embellished Georgette Midi Dress,4.4,10,3599.0,59.0,1475.0,INR,http://assets.myntassets.com/assets/images/200...,...,Sle███ Ap███els███,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",D-8███2nd███oor█████████OR-███████████████████...,"[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,2950.0
65,20046216,YK Disney,Girls Minnie Mouse Graphic Printed A-Line T-sh...,5.0,7,999.0,67.0,329.0,INR,http://assets.myntassets.com/assets/images/200...,...,CRO███OAD███LOT█████████LTD███,"[{""size"":""2-3Y"",""value"":""23.0in"",""value_name"":...","[""https://videos.myntassets.com/assets/videos/...",75/███eer███gar█████████ Ha███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,658.0
68,22590642,YU by Pantaloons,Round Neck Schiffli Tiered Cotton A-Line Dress,4.8,12,1499.0,52.0,719.0,INR,http://assets.myntassets.com/assets/images/225...,...,Wes███ry ███din█████████d_P████████████,"[{""size"":""XS"",""value"":""33.5in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",Wes███ry ███din█████████e L███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1438.0
69,13572604,Tokyo Talkies,Women Green Self Design Sheath Dress,4.2,58,1799.0,63.0,1799.0,INR,http://assets.myntassets.com/assets/images/pro...,...,REL███CE ███U K█████████ATE█████████,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...","[""https://videos.myntassets.com/assets/videos/...",3rd███oor███o. █████████Mai███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",dresses,2,3598.0
70,13649832,all about you,Black & Mustard Yellow Printed A-Line Dress,4.3,56,1999.0,63.0,1999.0,INR,http://assets.myntassets.com/assets/images/136...,...,REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","[""rw-13649832_cae700""]",3rd███oor███o. █████████Mai███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",dresses,2,3998.0
73,13387584,Wish Karo,Girls Black & White Printed Fit and Flare Silk...,4.1,11,1999.0,65.0,699.0,INR,http://assets.myntassets.com/assets/images/pro...,...,Kot███da ███est█████████Ltd███,"[{""size"":""0-3M"",""value"":""18.6in"",""value_name"":...","[""https://videos.myntassets.com/assets/videos/...","LL ███3, ███den█████████adu███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1398.0
76,13558254,Tokyo Talkies,Women Peach-Coloured Printed Fit and Flare Dress,4.1,934,1349.0,59.0,1349.0,INR,http://assets.myntassets.com/assets/images/pro...,...,REL███CE ███U K█████████ATE█████████,"[{""size"":""S"",""value"":""39.0in"",""value_name"":""Bu...","[""https://videos.myntassets.com/assets/videos/...",3rd███oor███o. █████████Mai███████████████████...,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",dresses,2,2698.0
79,13406942,Global Desi,Girls Blue Embroidered A-Line Denim Dress,4.8,8,1799.0,75.0,449.0,INR,http://assets.myntassets.com/assets/images/134...,...,OCH███AND███ACK█████████LIM██████,"[{""size"":""3-4Y"",""value"":""21.0in"",""value_name"":...","[""https://videos.myntassets.com/assets/videos/...",Bui███ng ███rat█████████eam███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,898.0
80,1341220,Miss Chase,Black & White Striped Belted Dress,4.4,22,1149.0,10.0,689.0,INR,http://assets.myntassets.com/assets/images/134...,...,CHA███LIF███YLE█████████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",Cha███Lif███yle█████████. 3███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1378.0
81,13387582,Wish Karo,Girls Black Polka Dot Printed Fit and Flare Dress,4.7,18,2123.0,65.0,743.0,INR,http://assets.myntassets.com/assets/images/133...,...,Kot███da ███est█████████Ltd███,"[{""size"":""0-3M"",""value"":""18.6in"",""value_name"":...","[""https://videos.myntassets.com/assets/videos/...","LL ███3, ███den█████████adu███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1486.0
83,13391540,Mast & Harbour,EcoVero Women Yellow & White Abstract Printed ...,4.1,576,1999.0,66.0,679.0,INR,http://assets.myntassets.com/assets/images/133...,...,SWARR,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",D-2███Sec███ 06█████████uta███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1358.0
85,13435624,Deewa,Women Navy Blue & Off-White Floral Print Maxi ...,4.1,28,2199.0,69.0,681.0,INR,http://assets.myntassets.com/assets/images/134...,...,Sun███ne ███t W██████,"[{""size"":""XS"",""value"":""6.5in"",""value_name"":""Sl...","[""https://videos.myntassets.com/assets/videos/...",DEE███E-1███ SE█████████ NO███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1362.0

Some basic insights from data:
Average rating: 3.5269999999999997
Maximum price: 5699.0
Minimum price: 279.0

Cleaned dataset saved successfully as cleaned_dresses.csv

FINAL SUMMARY:

- Worked on a dresses dataset containing product details like rating, price, discount, seller info, and categories.

- Loaded the dataset and explored its structure using head(), tail(), shape, columns, data types, and info().

- Checked missing values in columns such as discount, seller_name, what_customers_said, videos, and variations.

- Handled missing values by filling numeric columns with median and categorical columns with mode.

- Removed duplicate rows to ensure clean and accurate data.

- Cleaned the final_price column by removing currency symbols (₹) and converting it into numeric format.

- Created a new feature called total_amount using final_price × quantity.

- Performed filtering to display products with rating greater than 4.

- Generated basic insights such as average rating, maximum price, and minimum price from the dataset.

- Saved the cleaned dataset as 'cleaned_dresses.csv' for further analysis.